language: java
install: true
script:
  - ./integration-test.sh
after_success:
  - mvn clean cobertura:cobertura coveralls:report
deploy:
  provider: heroku
  api_key:
    secure: ab58f12f-6913-4c4e-b136-0fc772f4c9f2
  app: murmuring-meadow-58244
